version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    container_name: mm-ai-clip
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./checkpoints:/app/checkpoints:ro
      - ./data:/app/data
